### ISSUE TITLE
mp3ファイルをロード出来る様にしたい。

### ISSUE THREAD

**Issue by manntera** [manntera/chibitera-discord-system#25]
wavファイルは容量が多い。
GCSは通信容量に対する従量課金制なので、出来るだけ容量を渋りたい。
mp3の256kbpsで運用したい。

**Comment by furimu1234** [comment]
これは既存のファイルもすべてmp3に変更するの？
既存の奴はwavで継続？

**Comment by manntera** [comment]
私の方で随時wavからmp3に変更する。
私が変更漏れしてサービスが停止するより、wavのロード機能は残しておいた方が良いと思う。

音声ファイルのロードに関しては抽象化して実装するとこういう時面倒臭くないかも。
