### ISSUE TITLE
タイマーの区切り時間をチャットコマンドで指定できる様にしたい。

### ISSUE THREAD

**Issue by manntera** [manntera/chibitera-discord-system#28]

**Comment by manntera** [comment]
てすと

**Comment by manntera** [comment]
想定としては、作業者や内容によっては作業周期が早かったり遅かったりすると思うので、作業者自身でサイクルを調整できる様にするのが目的。

**Comment by manntera** [comment]
BOTがVCから退出した時にデフォルトにリセットする方針で実装(furimu君が)

**Comment by manntera** [comment]
これの実装って時間かかりそう？

**Comment by furimu1234** [comment]
1.5hくらいで出来そうな気がする

**Comment by manntera** [comment]
じゃーお願い出来ると嬉しいー

**Comment by furimu1234** [comment]
忘れてたけど、時間の指定方法どうしよう

mで単位を統一するか

1h1m1sみたいに指定できるようにするか

**Comment by manntera** [comment]
分単位でいいんじゃないかなー
(コマンド) 30
で30分になるって感じだと嬉しい

**Comment by furimu1234** [comment]
done: https://github.com/manntera/chibitera-discord-system/pull/48
